{% set name = "libcufile" %}
{% set version = "1.13.1.3" %}
{% set cuda_version = "12.8" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "sbsa-linux" %}  # [aarch64]
{% set extension = "tar.xz" %}  # [not win]

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/{{ name }}/{{ platform }}/{{ name }}-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: 34a4bfe8fe98cb97e7631dfd29969284287f7cf8e19b372d49a4ee8f1e7ed797  # [linux64]
  sha256: 3664a21fad7b7bb4424beec650fe4d1bee77062d4038427ba90bf4f5edf364fe  # [aarch64]

build:
  number: 1
  skip: true  # [not (linux64 or aarch64)]

requirements:
  build:
    - cf-nvidia-tools 1.*  # [linux]
    - patchelf <0.18.0                      # [linux]

outputs:
  - name: libcufile
    build:
      binary_relocation: false
      missing_dso_whitelist:
        - "*/libcuda.so.*"
        # The problem is that even though rdma-core is in the run requirements, the RDMA libraries (libmlx5.so.1, librdmacm.so.1, libibverbs.so.1) are still not being found during the build process. 
        #This suggests that the run_exports from rdma-core aren't being properly resolved during the build phase.
        - "*/libmlx5.so.*"
        - "*/librdmacm.so.*"
        - "*/libibverbs.so.*"
      # This is a workaround to ignore the overlinking error for problematic *.so files.
      # The reason is that in the Amazon Linux 2-based Docker container, there's py-lief version 0.12.3.
      # In the Rocky 8 container, there's 0.16.4, which seems to have this bug.
      # See also:
      # https://github.com/anaconda/docker-images/blob/main/anaconda-pkg-build/linux/rocky8/Dockerfile
      # https://github.com/conda/conda-build/issues/5665
      # https://github.com/conda-forge/conda-build-feedstock/pull/251
      # https://github.com/conda-forge/lief-feedstock/pull/57#issuecomment-2770881269
      # This workaround should be removed when the conda-build fix is merged/py-lief pinned and the rocky 8 docker image rebuilt.
      overlinking_ignore_patterns:  # [linux and aarch64]
        - "targets/{{ target_name }}/lib/libcufile*.so*"   # [linux and aarch64]
        - "lib/libcufile*.so*"                              # [linux and aarch64]
    files:
      - lib/libcufile*.so.*
      - targets/{{ target_name }}/lib/libcufile*.so.*
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - {{ stdlib("c") }}
      host:
        - rdma-core                             # [linux]
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - rdma-core  # [linux]
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      requires:
        - patchelf  # [linux]
      files:
        - test-rpath-main.sh
      commands:
        # Note that the version of libcufile does not match
        # {{ version.split(".")[0] }} but the major version of libcufile_rdma does
        # match that. Also we must drop the last component of the version when
        # finding the versioned .so file.
        {% set full_version = version.split(".")[:-1] | join(".") %}
        - test -L $PREFIX/lib/libcufile.so.0
        - test -L $PREFIX/lib/libcufile_rdma.so.{{ version.split(".")[0] }}
        - test -L $PREFIX/lib/libcufile.so.{{ full_version }}
        - test -L $PREFIX/lib/libcufile_rdma.so.{{ full_version }}
        - test -L $PREFIX/targets/{{ target_name }}/lib/libcufile.so.0
        - test -L $PREFIX/targets/{{ target_name }}/lib/libcufile_rdma.so.{{ version.split(".")[0] }}
        - test -f $PREFIX/targets/{{ target_name }}/lib/libcufile.so.{{ full_version }}
        - test -f $PREFIX/targets/{{ target_name }}/lib/libcufile_rdma.so.{{ full_version }}
        - bash test-rpath-main.sh
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_file: LICENSE
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: Library for NVIDIA GPUDirect Storage
      description: |
        The cuFile library provides a direct data path between GPU memory and storage.
      doc_url: https://docs.nvidia.com/gpudirect-storage/api-reference-guide/index.html

  - name: libcufile-dev
    build:
      run_exports:
        - {{ pin_subpackage("libcufile", max_pin="x") }}
      # This is a workaround to ignore the overlinking error for problematic *.so files.
      overlinking_ignore_patterns:  # [linux and aarch64]
        - "targets/{{ target_name }}/lib/libcufile*.so*"   # [linux and aarch64]
        - "lib/libcufile*.so*"                              # [linux and aarch64]
    files:
      - lib/libcufile*.so
      - lib/pkgconfig
      - targets/{{ target_name }}/include
      - targets/{{ target_name }}/lib/libcufile*.so
      - man/man3
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - {{ pin_subpackage("libcufile", exact=True) }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - libcufile-static >={{ version }}
    test:
      commands:
        - test -L $PREFIX/lib/libcufile.so
        - test -L $PREFIX/lib/libcufile_rdma.so
        - test -f $PREFIX/targets/{{ target_name }}/include/cufile.h
        - test -L $PREFIX/targets/{{ target_name }}/lib/libcufile.so
        - test -L $PREFIX/targets/{{ target_name }}/lib/libcufile_rdma.so
        - test -d $PREFIX/man/man3
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_file: LICENSE
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: Library for NVIDIA GPUDirect Storage
      description: |
        The cuFile library provides a direct data path between GPU memory and storage.
      doc_url: https://docs.nvidia.com/gpudirect-storage/api-reference-guide/index.html

  - name: libcufile-static
    files:
      - targets/{{ target_name }}/lib/libcufile*_static.a
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      commands:
        - test -f $PREFIX/targets/{{ target_name }}/lib/libcufile_static.a
        - test -f $PREFIX/targets/{{ target_name }}/lib/libcufile_rdma_static.a
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_file: LICENSE
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: Library for NVIDIA GPUDirect Storage
      description: |
        The cuFile library provides a direct data path between GPU memory and storage.
      doc_url: https://docs.nvidia.com/gpudirect-storage/api-reference-guide/index.html

  - name: gds-tools
    build:
      missing_dso_whitelist:
        - "*/libcuda.so.*"
    files:
      - gds/tools
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_version }}
        - libcufile-dev {{ version }}
        - libnuma  # [linux]
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - {{ pin_subpackage("libcufile", max_pin="x") }}
        - {{ pin_compatible("libnuma", max_pin="x") }}  # [linux]
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      requires:
        - patchelf  # [linux]
      files:
        - test-rpath-gds.sh
      commands:
        - test -d $PREFIX/gds/tools
        - bash test-rpath-gds.sh
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_file: LICENSE
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: Library for NVIDIA GPUDirect Storage
      description: |
        The cuFile library provides a direct data path between GPU memory and storage.
      doc_url: https://docs.nvidia.com/gpudirect-storage/api-reference-guide/index.html

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_file: LICENSE
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Library for NVIDIA GPUDirect Storage
  description: |
    The cuFile library provides a direct data path between GPU memory and storage.
  doc_url: https://docs.nvidia.com/gpudirect-storage/api-reference-guide/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
  feedstock-name: libcufile
